---
# tasks file for control
    - name: Install tools
      apt: name={{ item }} state=present update_cache=no
      with_items:
       - curl
       - python-httplib2
       - python-pip

    - name: Install pyton package
      pip: name=boto state=present