---
 - hosts: loadbalancer
   become: true
   tasks:
    - name: Check nginx status
      command: service nginx status

    - name: Ensure nginx listen on port 80
      wait_for: port=80 timeout=1

 - hosts: webserver
   become: true
   tasks:
    - name: Check apache2 status
      command: service apache2 status

    - name: Ensure apache2 listen on port 80
      wait_for: port=80 timeout=1

 - hosts: database
   become: true
   tasks:
    - name: Check mysql status
      command: service mysql status

    - name: Ensure mysql listen on port 3306
      wait_for: port=3306 timeout=1
      