---
 - hosts: loadbalancer
   become: true
   tasks:
    - name: Stopping nginx
      service: name=nginx state=stopped

 - hosts: webserver
   become: true
   tasks:
    - name: Stopping apache2
      service: name=apache2 state=stopped

 - hosts: database
   become: true
   tasks:
    - name: Restarting mysql
      service: name=mysql state=restarted

 - hosts: webserver
   become: true
   tasks:
    - name: Starting apache2
      service: name=apache2 state=started

 - hosts: loadbalancer
   become: true
   tasks:
    - name: Starting nginx
      service: name=nginx state=started
