---
 - hosts: loadbalancer
   become: true
   tasks:
    - name: Stopping nginx
      service: name=nginx state=stopped

    - wait_for: port=80 state=drained

 - hosts: webserver
   become: true
   tasks:
    - name: Stopping apache2
      service: name=apache2 state=stopped

    - wait_for: port=80 state=stopped

 - hosts: database
   become: true
   tasks:
    - name: Restarting mysql
      service: name=mysql state=restarted

    - wait_for: port=3306 state=started

 - hosts: webserver
   become: true
   tasks:
    - name: Starting apache2
      service: name=apache2 state=started

    - wait_for: port=80

 - hosts: loadbalancer
   become: true
   tasks:
    - name: Starting nginx
      service: name=nginx state=started

    - wait_for: port=80
