---
# tasks file for nginx
    - name: Install nginx and tools
      apt: name={{ item }} state=present update_cache=no
      with_items:
       - nginx
       - python-httplib2

    - name: Configure nginx
      template: src=demo_lb.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
      with_dict: "{{ sites }}"
      notify: Restart nginx

    - name: Get active sites
      shell: ls -1 /etc/nginx/sites-enabled
      register: active

    - name: De-activate uneccesary config
      file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
      with_items: "{{ active['stdout_lines'] }}"
      when: item not in sites
      notify: Restart nginx

    - name: Acivate demo config
      file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
      with_dict: "{{ sites }}"
      notify: Restart nginx

    - name: Ensure nginx running
      service: name=nginx state=started enabled=yes