---
 - hosts: control
   gather_facts: false
   tasks:
    - name: Create All-New-OLX VPC
      ec2_vpc_net:
        name: All-New-OLX VPC
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: "{{ aws_tags }}"
        state: absent
        cidr_block: 10.77.0.0/16
      register: vpc

    - name: Create All-New-OLX Subnet Public 1
      ec2_vpc_subnet:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: "{{ aws_tags }}"
        state: absent
        vpc_id: vpc-edaa1389
        cidr: 10.77.0.0/24
        az: ap-southeast-1a
      register: public1

    - name: Create All-New-OLX Subnet Public 2
      ec2_vpc_subnet:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: "{{ aws_tags }}"
        state: absent
        vpc_id: vpc-edaa1389
        cidr: 10.77.1.0/24
        az: ap-southeast-1b
      register: public2

