---
 - hosts: control
   gather_facts: false
   tasks:
    - name: Create Test VPC
      ec2_vpc_net:
        name: Test VPC
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        cidr_block: 10.77.0.0/16
        tags:
          finance_region: Indonesia
        state: present

