---
 - hosts: control
   gather_facts: false
   tasks:
    - name: Create All-New-OLX VPC
      ec2_vpc_net:
        name: All-New-OLX VPC
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: "{{ aws_tags }}"
        state: present
        cidr_block: 10.88.0.0/16
      register: vpc

    - name: Create All-New-OLX Subnet Public 1
      ec2_vpc_subnet:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: { "Name" : "Public-1" }
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.88.0.0/24
        az: "{{ aws_az_1 }}"
      register: public1

    - name: Create All-New-OLX Subnet Public 2
      ec2_vpc_subnet:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: { "Name" : "Public-2" }
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.88.1.0/24
        az: "{{ aws_az_2 }}"
      register: public2

    - name: Create All-New-OLX Subnet Privat 1
      ec2_vpc_subnet:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: { "Name" : "Privat-1" }
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.88.2.0/23
        az: "{{ aws_az_1 }}"
      register: privat1

    - name: Create All-New-OLX Subnet Privat 2
      ec2_vpc_subnet:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: { "Name" : "Privat-2" }
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.88.4.0/23
        az: "{{ aws_az_2 }}"
      register: privat2

    - name: Create All-New-OLX IGW
      ec2_vpc_igw:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
      register: igw

    - name: Create All-New-OLX NAT
      ec2_vpc_nat_gateway:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        state: present
        subnet_id: "{{ public1.subnet.id }}"
        wait: yes
        if_exist_do_not_create: yes
      register: nat

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: { "Name" : "Public route" }
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        subnets:
         - "{{ public1.subnet.id }}"
         - "{{ public2.subnet.id }}"
        routes:
         - dest: 0.0.0.0/0
           gateway_id: "{{ igw.gateway_id }}"
      register: public_route

    - name: Set up privat subnet route table
      ec2_vpc_route_table:
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        tags: { "Name" : "Privat route" }
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        subnets:
         - "{{ privat1.subnet.id }}"
         - "{{ privat2.subnet.id }}"
        routes:
         - dest: 0.0.0.0/0
           gateway_id: "{{ nat.nat_gateway_id }}"
      register: private_route

    - name: Create Redis subnet group
      elasticache_subnet_group:
        name: All-New-OLX
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        state: present
        description: All-New-OLX Redis subnet group
        subnets:
         - "{{ privat1.subnet.id }}"
         - "{{ privat2.subnet.id }}"
      register: elasticache_subnet

    - name: Create Redis security groups
      ec2_group:
        name: Redis security groups
        description: Redis security groups
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
         - proto: tcp
           from_port: 6379
           to_port: 6379
           cidr_ip: "{{ vpc.vpc.cidr_block }}"
      register: redis_sg

    - name: Create All-New-OLX Redis Elasticache
      elasticache:
        name: All-New-OLX-redis
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        state: absent
        engine: redis
        cache_engine_version: 3.2.4
        cache_parameter_group: default.redis3.2
        security_group_ids: "{{ redis_sg.group_id }}"
        cache_subnet_group: All-New-OLX
        node_type: cache.t2.medium
        num_nodes: 1
        cache_port: 6379
        zone: "{{ aws_az_1 }}"
        wait: yes



