---
 - hosts: database
   become: true
   tasks:
    - name: Install mysql-server
      apt: name=mysql-server state=present update_cache=no

    - name: Ensure mysql running
      service: name=mysql state=started enabled=yes