---
 - hosts: control
   gather_facts: false
   tasks:
    - name: Create All-New-OLX VPC
      ec2_vpc:
        state: absent
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        cidr_block: 10.77.0.0/16
        resource_tags: { "Name" : "All-New-OLX VPC" }
        subnets:
          - cidr: 10.77.0.0/24
            az: "{{ aws_az_1 }}"
            resource_tags: { "Name" : "Public-1" }
          - cidr: 10.77.1.0/24
            az: "{{ aws_az_2 }}"
            resource_tags: { "Name" : "Public-2" }
          - cidr: 10.77.2.0/23
            az: "{{ aws_az_1 }}"
            resource_tags: { "Name" : "Privat-1" }
          - cidr: 10.77.4.0/23
            az: "{{ aws_az_2 }}"
            resource_tags: { "Name" : "Privat-2" }
        internet_gateway: yes
        wait: yes
        route_tables:
          - subnets:
              - 10.77.0.0/24
              - 10.77.1.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
      register: vpc

    - name: Create All-New-OLX IGW
      ec2_vpc_igw:
        state: absent
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc.vpc_id }}"
      register: igw

    - name: Create All-New-OLX NAT
      ec2_vpc_nat_gateway:
        state: absent
        aws_access_key: "{{ vault_access_key }}"
        aws_secret_key: "{{ vault_secret_key }}"
        region: "{{ aws_region }}"
        subnet_id: "{{ vpc.subnets[1].id }}"
        wait: yes
        if_exist_do_not_create: yes
        nat_gateway_id: nat-0ababf73da50bf9bb
      register: new_nat_gateway

