---
 - hosts: webserver
   become: true
   tasks:
    - name: Install webserver component
      apt: name={{ item }} state=present update_cache=true
      with_items:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv

    - name: Ensure apache2 running
      service: name=apache2 state=started enabled=yes